# Generated by Django 5.1.3 on 2024-11-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='image.png', upload_to='media/'),
        ),
    ]
