# Generated by Django 5.1.3 on 2024-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='image.png', upload_to='media/', verbose_name='Image'),
        ),
    ]
