# Generated by Django 5.1.3 on 2024-11-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
