# Generated by Django 5.1.3 on 2024-11-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipe_favorite_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
