# Generated by Django 5.1.3 on 2024-11-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
    ]
